### ISSUE TITLE
Error on fresh install: No lockfile found. Unable to read locked packages

### ISSUE THREAD

**Issue by postalservice14** [thecodingmachine/mouf#102]
I get this error with a blank project.

composer.json

``` json
{
    "autoload" : {
        "psr-4" : {
            "MyNamespace\\" : "src/"
        }
    },
    "require": {
        "mouf/mouf": "~2.1"
    },
    "minimum-stability": "dev"
}
```

See full verbose output here: https://gist.github.com/postalservice14/f4689b3820895e217c55

**Comment by moufmouf** [comment]
Hi John!

Mouf 2.1 is completely in development and really broken now.
We have a problem on Mouf website because we should display the doc of Mouf 2.0 first.

Please try this instead:

```
{
    "autoload" : {
        "psr-4" : {
            "MyNamespace\\" : "src/"
        }
    },
    "require": {
        "mouf/mouf": "~2.0.0"
    }
}
```

It should definitely work better. Let me know if you face any problems :)
