### ISSUE TITLE
[CRITICAL] - possible instance deletion

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/mouf#116]
When removing instances from an instance's 'collection' property, e.g. `myInstance.children`, if you try to remove (drag & drop to trash) one of those children, then the order of the remaining ones has changed, **BUT NOT VISUALLY**, which leads to a lot of missunderstanding : 
- order has changed, and you dont know unless you refresh the page
- if u then remove a second child, then you will in fact remove yet another one. This case is the worst because if this was an anomnymous instances, then you just lost it :(

**Comment by moufmouf** [comment]
@Cach54 Seems this is related to your problem about Evolucolumns hard to edit.
Will fix.
