### ISSUE TITLE
Impossible to delete or rename an instance in the GUI.

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/mouf#4]
Impossible to delete or rename an instance in the GUI.

**Comment by moufmouf** [comment]
Unable to reproduce.
I can use the "rename" and "delete" button fine.

Can you give me more context?

**Comment by moufmouf** [comment]
Ok, the problem occurs only on anonymous instances

**Comment by vaidiep** [comment]
The probleme is when we want to delete a class that contains instances in the constructor arguments

**Comment by moufmouf** [comment]
Fixed
