### ISSUE TITLE
APCU in PHP 5.5 generates notice in (red) purge cache

### ISSUE THREAD

**Issue by nguyenk** [thecodingmachine/mouf#52]
Cannot purge cache when using PHP 5.5 / APCU : 
<code>Notice: Undefined index: info in /var/www/soyooz/vendor/mouf/utils.cache.apc-cache/src/Mouf/Utils/Cache/ApcCache.php on line 206</code>

However, it works when purging code cache before ...

**Comment by moufmouf** [comment]
I assume the problem was coming from an early version of APCU that was not compliant with the APC API.
The problem did not occur again so I'm closing the issue.
