### ISSUE TITLE
"Web directory access" instructions have a missing \n

### ISSUE THREAD

**Issue by WizMik** [thecodingmachine/mouf#53]
When installing a new mouf application and running it for the first time, I get the "Web directory must be writable for the Apache user" message with the instructions below :

sudo chown www-data:www-data /home/lincoln/www.drupal
sudo chown www-data:www-data /home/lincoln/www.drupal/vendor/mouf/moufsudo chown www-data:www-data /home/lincoln/www.drupal/mouf

A newline separator is missing between the second and third instruction.

**Comment by moufmouf** [comment]
Actually, we should improve the way rights are managed (we might want to propose to share a group "write" right on the files, which is cleaner)
