### ISSUE TITLE
Impossible to connect to my database using DB_HOST=localhost

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/mouf#54]
Hi,

I have two mysql servers running on my machine, one on the port 8889 and one on the port 3306.

In the config page, when I set my database connection to:
DB_HOST: localhost
DB_PORT: 3306

The server used was the server on the port 8889.

To fix it, I had to set my database connection to:
DB_HOST: 127.0.0.1
DB_PORT: 3306

**Comment by moufmouf** [comment]
Now, if a port is specified, it is enforced. Before, MySQL was automatically switching on Unix sockets (for performance reasons.)
