### ISSUE TITLE
Search for anonymous instances is ko

### ISSUE THREAD

**Issue by npeguin** [thecodingmachine/mouf#56]
When we click on "Show anonymous instances" button the url destination is "/vendor/mouf/mouf/mouf/<?echo ROOT_URL ?>mouf/?selfedit=false&query=&show_anonymous=true" -> 404

The part "<?echo ROOT_URL ?>mouf/" seems to be erroneous

**Comment by moufmouf** [comment]
Seems to be already fixed. Maybe you are not using the latest version?
