### ISSUE TITLE
"Cannot redeclare class jsonschema\\constraints\\strings"

### ISSUE THREAD

**Issue by camkLcbr** [thecodingmachine/mouf#71]
After updating my `composer.phar` and installing Mouf, I run into this error when reaching the validation screen : 

``` php
PHP Fatal error: include() : cannot redeclare class jsonschema\\constraints\\strings in /var/www/project/vendor/mouf/mouf/vendor/composer/ClassLoader.php on line 377
```

My Php version is **5.4.4-14**, Apache is on **2.2.22** version and the server runs Debian **3.2.57-3 x86_64**.

Here's the stack trace displayed on the error_log : 

![stack_trace_1](https://cloud.githubusercontent.com/assets/3781258/3330068/f3c79762-f7cc-11e3-8fef-733bca17d827.PNG)

![stack_trace_2](https://cloud.githubusercontent.com/assets/3781258/3330070/f85bdc66-f7cc-11e3-9d5e-e00b62fa3ea3.PNG)

**Comment by moufmouf** [comment]
Problem seems to be related to PHP installation upgrading from PHP 5.4.4 to a newer PHP 5.5 version solved the issue.
Seems to be due to a bug deep in PHP. Any person having this problem is encouraged to upgrade.
