### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by FloSeas** [thecodingmachine/mouf#78]
Hello, me again!

Just i was wondering if there is a way the show errors on views on development mode?

Because when i try to debug it's pretty hard, just seeing a blank page and need to debug with brain compilator.

Even a classical print_r();exit does not work.

Is there an option to activate error showing on developpement mode in views?

**Comment by moufmouf** [comment]
Hi!

There is absolutely nothing in Mouf / Splash preventing the display of errors. error_reporting is not overloaded / modified, so it should really work like in a classical PHP application.

print_r();exit; should definitely display something. Maybe it is printed but you don't see it on the screen? For instance, if you are printing into a script tag in a view, you would see the result in the HTML source but not in the browser. Can this be related?

**Comment by FloSeas** [comment]
don't really know, all i see is a blank page so i don't really understand, may it's cloud9 php configuration, i'll take a look and answer back to you

**Comment by FloSeas** [comment]
Ok solved it, was by default error are not displayed due to php.ini config on cloud9, solved it by enabling error log and error display, feel way much better, ty
