### ISSUE TITLE
MoufPress - config.php and wp-config.php incompatibility

### ISSUE THREAD

**Issue by cdupoiron** [thecodingmachine/mouf#82]
Hello,

I use moufpress and database.tdbm. The applicaiton load database.tdbm config file and wordpress wp-config file and both files have the same constants (DB_HOST, DB_PORT... ).

`Notice: Constant DB_HOST already defined in *\config.php on line 16`

Do I miss something?

Thx

**Comment by cdupoiron** [comment]
One solution can be:
In Mouf configuration (mouf/mouf/config), add others constants (DB_DAO_HOST, DB_DAO_PORT..).
Then go to Instance "dbConnection" and modify Public properties to use new constants.

Is it correct to do so?

**Comment by moufmouf** [comment]
Hi!

That's exactly what I was going to say!

TDBM is creating constants that are named `DB_HOST`, `DB_PORT`... On most projects, this is not an issue, but when you use Wordpress with TDBM, there is a conflict.

You can just rename the constants in Mouf (In Mouf menu > Project > Edit configuration).
Then, go to the "dbConnection" instance and point the public properties to the new constants and you are done!

This is completely correct, and the right way to solve this issue.

**Comment by cdupoiron** [comment]
Hi :)

Thank you for your answer and your work !
