### ISSUE TITLE
Open graph implementation

### ISSUE THREAD

**Issue by Ngob** [thecodingmachine/mouf#85]
It would be sweet to have an open-graph support by default

https://developers.facebook.com/docs/opengraph

**Comment by moufmouf** [comment]
I guess you are speaking about the mouf-php.com website?

**Comment by moufmouf** [comment]
If you want to write a special `OpenGraphWidget` class that implements `HtmlElementInterface`, you should put it in the appropriate package, like: mouf/html.widgets.base-html-widget
