### ISSUE TITLE
Can't set variable using getProperty() and setValue() on an instance

### ISSUE THREAD

**Issue by vaidiep** [thecodingmachine/mouf#9]
Can't set variable using getProperty() and setValue() on an instance.

Code: 
$nullWithHyphen = $moufManager->createInstance("Mouf\Utils\Common\Formatters\NullTransformationFormatter");
    // Let's set a name for this instance (otherwise, it would be anonymous)
    $nullWithHyphen->setName("replaceNullWithHyphen");
    $nullWithHyphen->getProperty("value")->setValue("-");

Class:  class NullTransformationFormatter implements FormatterInterface {

```
/**
 * The value to replace the NULL value with.
 * 
 * @Property
 * @Compulsory
 * @var string
 */
public $value;

/**
 * Whether the value passed above should be translated or not.
 * 
 * @Property
 * @var bool
 */
public $useI18n;

public function __construct($value=null, $useI18n=false) {
    $this->value = $value;
    $this->useI18n = $useI18n;
}

/**
 * Formats the value.
 *
 * @param string $value
 */
public function format($value) {
    if ($value ===  null) {
        if (!$this->useI18n) {
            return $this->value;
        } else {
            return iMsg($this->value);
        }
    } else {
        return $value;
    }
}
```

}

Stack: Fatal error: Uncaught exception 'Mouf\MoufException' with message 'In MoufInstanceProperty::setValue, the property 'value' instance 'replaceNullWithHyphen' of class 'Mouf\Utils\Common\Formatters\NullTransformationFormatter' is supposed to be a MoufInstanceDescriptor (or null).' in C:\Users\Pierre\Documents\SIHP\src\vendor\mouf\mouf\src\Mouf\MoufInstancePropertyDescriptor.php on line 159
( ! ) Mouf\MoufException: In MoufInstanceProperty::setValue, the property 'value' instance 'replaceNullWithHyphen' of class 'Mouf\Utils\Common\Formatters\NullTransformationFormatter' is supposed to be a MoufInstanceDescriptor (or null). in C:\Users\Pierre\Documents\SIHP\src\vendor\mouf\mouf\src\Mouf\MoufInstancePropertyDescriptor.php on line 159
Call Stack
# Time    Memory  Function    Location

1   0.0006  153912  {main}( )   ..\install.php:0
2   0.0411  1193776 Mouf\MoufInstancePropertyDescriptor->setValue( )    ..\install.php:22

**Comment by moufmouf** [comment]
The issue: when using $instanceDescriptor->getProperty on a variable from the constructor that has no type defined, MoufInstanceDescriptor assumes this must be a class.
By default, we should assume string.
